#Return Codes from code generator
TASK_SUCCESSFUL = 0;
REQUEST_CLASS_NAME = 101;
REQUEST_CLASS_MODIFIER = 102;
REQUEST_MSG_TO_PRINT = 103;
REQUEST_METHOD_NAME = 104;
REQUEST_METHOD_RETURN_TYPE = 105;
REQUEST_WANT_MORE_PARAMETERS = 106;
REQUEST_METHOD_PARAMETER_TYPE = 107;
REQUEST_METHOD_PARAMETER_NAME = 108;
REQUEST_CONTEXT_NAME=109;
REQUEST_VARIABLE_NAME=110;
REQUEST_VARIABLE_TYPE=111;
REQUEST_VARIABLE_MODIFIER=112;
REQUEST_FUNCTION_TO_CALL=113;